[package]
name = "norgopolis-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.0"
tokio = "1.28.1"
tonic = "0.9.2"
